---
title: Stimulus randomization
author: Dan Yurovsky
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: show 
---


```{r setup, include=FALSE}
# load packages
library(knitr)
library(here)
library(janitor)
library(tidyverse)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = FALSE, tidy = FALSE)

theme_set(theme_classic(base_size = 16))
```

```{r read-data}
stim_table <- read_csv(here("stimuli/stimuli_table.csv"))
```

Constraints:

*  every participant sees all 10 targets once

*  1/2 first round 1/2 last around

*  1/2 child, 1/2 parent

* at least 2 judgments

*  each from a different subject pair

```{r setup-stims}
start_stims <- stim_table %>%
  group_by(subid, target) %>%
  arrange(trial) %>%
  mutate(occurrence = 1:n())  %>%
  ungroup()

nested_stims <- start_stims %>%
  group_by(occurrence, person, target) %>%
  nest() %>%
  rowwise() %>%
  mutate(rows = nrow(data)) %>%
  ungroup()
```

```{r randomize}
randomize <- function() {
  
  for(i in 1: (floor(nrow(stims) / 10))) {
    
    print(i)
    
    start <- nested_stims %>%
      group_by(target) %>%
      summarise(rows = sum(rows)) %>%
      sample_n(10, weight = rows) %>%
      select(-rows) %>%
      left_join(nested_stims, by = "target") %>%
      arrange(desc(rows)) %>%
      group_by(target) %>%
      slice(1) %>%
      ungroup() %>%
      arrange(rows) %>%
      select(-data, -rows)

    
    occurrence_count <- start %>%
      group_by(occurrence) %>%
      count()
    
    one_diff <- 5 - occurrence_count %>% 
      filter(occurrence == 1) %>% 
      pull(n)
    
    one_start <- start %>%
      filter(occurrence == 1)
    
    two_start <- start %>%
      filter(occurrence == 2)
    
    if(one_diff < 0) {
      one_change <- one_start %>%
        slice(1:(-one_diff)) %>%
        mutate(occurrence = 2) 
      
      start <- start %>%
        anti_join(one_change, by = c("target", "person")) %>%
        bind_rows(one_change)
      
    }
    
    if(is.na(one_diff)) {
      one_diff <- 5
    }
    
    if(one_diff > 0) {
      two_change <- two_start %>%
        slice(1:one_diff) %>%
        mutate(occurrence = 1) 
      
      start <- start %>%
        anti_join(two_change, by = c("target", "person")) %>%
        bind_rows(two_change)
      
    }
    
    subj_data <- start %>%
      inner_join(stims, by = c("target", "person", "occurrence")) %>%
      group_by(target, person, occurrence) %>%
      sample_n(1)
    
    stims <<- anti_join(stims, subj_data, 
                        by = c("audio", "subid", "trial", "target", "leftpic", 
                               "rightpic", "correct", "person", "occurrence"))
    
    nested_stims <-  stims %>%
    group_by(occurrence, person, target) %>%
    nest() %>%
    rowwise() %>%
    mutate(rows = nrow(data)) %>%
    ungroup()
    
    subjs <<- bind_rows(subjs, subj_data %>% mutate(subject = i))
  }
}
```

```{r out}
subjs <- tibble()
stims <- start_stims

try(randomize(), silent = T)

write_csv(subjs, here("output/random_stims.csv"))
```

